= Exploring strategies for users and credentials

[#update-container]
== Updating the container image
In the previous exercises, we've created users and added ssh keys at install time, either via a blueprint file 
passed to `bootc-image-buider` or via kickstart to Anaconda. There are many ways and many reasons why handling 
users would happen at any particular stage of the process, during deployment or after install via network authentication.

In addition to adding users during the creation of a host system, via `bootc-image-buider`, `cloud-init`, or some other means, we can also create users during
the creation of the bootc image. This can be useful in certain cases where particular emergency users are needed in environments with limited connectivity. 
The users and credentials would be tied to the image, which means controlling how secrets are used in the build are important to understand before going 
down this path. In this case, we'll be using a fairly simple means to get the lab host user's credentials into the VM, but you will want to explore more 
before making this choice in your own environment.

On the host system (make sure the prompt shows `[lab-user@hypervisor rh-summit-2024-lb1506]$`), you can now edit the `Containerfile` with the following contents:

[source,dockerfile]
----
FROM registry.redhat.io/rhel9/rhel-bootc:9.4

COPY certs/004-summit.conf /etc/containers/registries.conf.d/004-summit.conf

COPY templates/30-auth-system.conf /etc/ssh/sshd_config.d/30-auth-system.conf
ARG SSHPUBKEY
RUN mkdir -p /usr/ssh
RUN echo ${SSHPUBKEY} > /usr/ssh/root.keys && chmod 0600 /usr/ssh/root.keys

RUN dnf install -y httpd
RUN echo "Hello Red Hat" > /var/www/html/index.html
RUN systemctl enable httpd
----

We will use some addtional build features of `podman` to get the credentials we want to embed in the image.

  * `ARG SSHPUBKEY` -> adds a build-time argument for `podman` to be used as the public ssh key
  * `RUN mkdir -p /usr/ssh` -> create the new keys directory
  * `RUN echo ${SSHPUBKEY} > /usr/ssh/root.keys && chmod 0600 /usr/ssh/root.keys` -> write the build time argument as the ssh key for the `root` user

You can now build the new container image with with the following command, note the `--build-arg` argument and how we populate the variable:

[source,bash]
----
podman build --build-arg SSHPUBKEY="$(cat ~/.ssh/id_rsa.pub)" --file Containerfile --tag summit.registry/lb1506:bootc
----

And make sure to push it to the registry:

[source,bash]
----
podman push summit.registry/lb1506:bootc
----

[#update-vm]
== Updating the virtual machine

The virtual machine you have been working with during this workshop should still be running. You can check this with

[source,bash]
----
virsh --connect qemu:///system list
----

And the output should contain a virtual machine called `qcow`.

Now you can ssh into the virtual machine

[source,bash]
----
ssh lab-user@qcow-vm
----

And check the bootc status:

[source,bash]
----
sudo bootc status
----

The output should look like this:

[source,yaml]
----
apiVersion: org.containers.bootc/v1alpha1
kind: BootcHost
metadata:
  name: host
spec:
  image:
    image: summit.registry/lb1506:bootc
    transport: registry
  bootOrder: default
status:
  staged: null
  booted:
    image:
      image:
        image: summit.registry/lb1506:bootc
        transport: registry
      version: 9.20240707.0
      timestamp: null
      imageDigest: sha256:da0fa085029428483c884845712e20785bcff14a54bda301f66310a13df2872a
    cachedUpdate: null
    incompatible: false
    pinned: false
    ostree:
      checksum: 21d4df251895c2d84fff4301b734435f4971a5cac16c76d886b7848d939b73e3
      deploySerial: 0
  rollback: null
  rollbackQueued: false
  type: bootcHost
----

We can trigger the update and immediately reboot by using the `--apply` flag:

[source,bash]
----
sudo bootc update --apply
----

The output should look something like this:

----
Loading usr/lib/ostree/prepare-root.conf
Queued for next boot: summit.registry/lb1506:bootc-auth
  Version: 9.20240501.0
  Digest: sha256:c5a5bc63cc5d081c528c82a177d0c5eac996a16fa3a651f93d07825302ff5336
Total new layers: 73    Size: 947.9 MB
Removed layers:   6     Size: 2.3 kB
Added layers:     6     Size: 2.2 kB
Rebooting system
----

[#testing]
== Testing the changes

You can now login to the virtual machine with the newly added root credentials:

[source,bash]
----
ssh root@qcow-vm
----

And check once again the status of bootc:

[source,bash]
----
bootc status
----

The output should look like this:

[source,yaml]
spec:
  image:
    image: summit.registry/lb1506:bootc-auth
    transport: registry
  bootOrder: default
status:
  staged: null
  booted:
    image:
      image:
        image: summit.registry/lb1506:bootc-auth
        transport: registry
      version: 9.20240501.0
      timestamp: null
      imageDigest: sha256:b57df8b24f7ddaf39ade0efe02d203e4fcd63deca2a9fd47f4af5c2cc3fcd017
    cachedUpdate: null
    incompatible: false
    pinned: false
    ostree:
      checksum: 09221f57a440c585ebd5e77e7b2fe6d4a8d9fab083c2e62dad4e322c16ec6bed
      deploySerial: 0
  rollback:
    image:
      image:
        image: summit.registry/lb1506:bootc-auth
        transport: registry
      version: 9.20240501.0
      timestamp: null
      imageDigest: sha256:d2f01ccf89c4ef6c4cc7d61982e4a83d3fc222c9028ab3eacc4ea0667df436e9
    cachedUpdate:
      image:
        image: summit.registry/lb1506:bootc-auth
        transport: registry
      version: 9.20240501.0
      timestamp: null
      imageDigest: sha256:b57df8b24f7ddaf39ade0efe02d203e4fcd63deca2a9fd47f4af5c2cc3fcd017
    incompatible: false
    pinned: false
    ostree:
      checksum: dbc49413600f67d5ba26dbf6f3bf441ea1824b5091a6e2038901263b3262651f
      deploySerial: 0
  rollbackQueued: false
  type: bootcHost
----
