WARNING: DELETE ME

= Building a very simple bootc image

[#write]
== Write the Containerfile

NOTE: The more advanced `vim` editor is also available. Users of `vim` should already know the basics
of opening, saving and exiting the editor. The instructions will reflect the `nano` commands.

Let's start with a typical application container and convert it to an image mode host. We'll start
with something simple, a basic webserver. To start the editor:

[source,bash]
----
nano Containerfile
----

WARNING: Move the example Containerfile here as a starting point otherwise this won't make sense

[source,dockerfile]
----
FROM registry.access.redhat.com/ubi9/ubi

RUN dnf install -y httpd
RUN echo "Hello Red Hat" > /var/www/html/index.html

ENTRYPOINT /usr/sbin/httpd -DFOREGROUND
----

A brief explanation of the lines above:

  * `FROM` -> the base container image
  * `RUN` -> simple shell command that is run in the container at build time
  * `ENTRYPOINT` -> the command that will be executed by default at run time



You can check your `Containerfile` file was properly saved by listing it's current contents:

[source,bash]
----
cat Containerfile
----

NOTE: All the Containerfiles also exist in the `examples/` directory.

[#build]
== Build the container

After defining the `Containerfile` you can build it by using the `podman build` command with
the following arguments:

  * `--file Containerfile` -> what Containerfile to use for the build
  * `--tag summit.registry/lb1506:latest` -> the "tag" or name of the resulting container

Of course, the filename and tag can be changed, but the rest of this workshop is geared towards using
the above (`Containerfile` and `summit.registry/lb1506:latest`), so please try using them.

----
podman build --file Containerfile --tag summit.registry/lb1506:latest
----

If the above command is succesful, the last two lines of the output should read like this:

----
Successfully tagged summit.registry/lb1506:latest
f1bea10eb37acf2e78a9b01c6242110c1901adbaf40dbce479241c6c735c58da
----

[#test]
== Test the containerized application

Now that the application is ready, you can run it:

[source,bash]
----
podman run --rm --name http-test --detach --publish 80:80 summit.registry/lb1506:latest
----

Test that it is running:

[source,bash]
----
podman ps | grep http-test
----

The output of the command above should read like this:

----
06a7bdb1950b  summit.registry/lb1506:latest    15 seconds ago  Up 16 seconds  0.0.0.0:80->80/tcp    http-test
----

And you can test the application:

[source,bash]
----
curl http://localhost/
----

The result of the command above should be the "Hello Red Hat" string from the Containerfile:

----
Hello Red Hat
----

You should preserve this image by tagging it:

----
podman tag summit.registry/lb1506:latest summit.registry/lb1506:app
----

And you should also remove the running container:

----
podman stop http-test
----

Congratulations, you now know how to run a containerized web server! Let's see how you can tranform this simple application into a bootc container.
