= Creating an inner loop for system design
[#test]
== Testing a bootc image as a container

Being able to make changes, build, and run an application locally is part of what is called
the 'inner loop' of application development. One advantages of image mode, the use of 
standard container tools brings this 'inner loop' capability to the design and development of 
standard operating system builds. 

While not every nuance of system behavior can be tested this way (eg SELinux polices), this still 
can greatly reduce the amount of time usually needed to test changes to configurations, software installations, etc.

You can launch this bootc container like any other application container, `podman` will
start `systemd` by default. Using `--detach` will help ensure that `systemd` is PID1 and 
the bootc image will initialize as intended when running as a host.

[source,bash]
----
podman run --rm --name http-test --detach --publish 80:80 summit.registry/lb1506:bootc
----

Test that it is running:

[source,bash]
----
podman ps | grep http-test
----

The output of the command above should resemble:

----
06a7bdb1950b  summit.registry/lb1506:latest    15 seconds ago  Up 16 seconds  0.0.0.0:80->80/tcp    http-test
----

And you can test the webserver:

[source,bash]
----
curl http://localhost/
----

The result of the command above should be the latest index.html we created.

----
Hello Red Hat Summit Connect 2024!!
----

Could we have caught our issue with the index not changing if we'd done testing as a container? Let's get a 
shell in our running container and have a look.

[source,bash]
----
podman exec -it http-test /bin/bash
----

We are now root inside the container. Look for the current index page in `/usr/share`


[source,bash]
----
cat /usr/share/www/index.html
----
----
Hello Red Hat Summit Connect 2024!!
----

What about the first index page we made in `/var`?
[source,bash]
----
cat /var/www/index.html
----
----
Hello Red Hat Summit
----

It's still there but not being served because of the change to the Apache configs.

[source,bash]
----
grep DocumentRoot /etc/httpd/conf/httpd.conf
----

Once you're done testing, go ahead and stop the running container:

[source,bash]
----
podman stop http-test
----
