= Deploy a bootc virtual machine with prebuilt image

In this lab, you will build a `qcow2` disk image out of the bootc image and then boot
a virtual machine using it.

`qcow2` is a standard file format used by the Linux virtualization system.

[#config]
== Create the config for building the virtual machine image

You may have noticed the bootc image we've created does not include any login credentials. Not a 
typical concern for an application container, but as a host we will very likely need to interact
at some point.

Since we are defining an image to be shared by multiple hosts in multiple different environments,
users and authentication is likely to be handled at the deployment stage, not the build stage.

NOTE: There are cases where it may be useful for a user and credentials to be added to an image, 
as a 'break glass' emergency login for example.

To add a user during the conversion to a disk image, you need to create a JSON file with the credentials.
This config file will be used by `bootc-image-builder` to customize the final disk image.

A ssh key has been generated in the Setup section of this lab. You can view the public part like this:

[source,bash]
----
cat ~/.ssh/id_rsa.pub
----

The output should look something like this (Example):

----
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAuXnpoluye+KM+9tvIAdHf+F0IHh+K73tlcjEG8LJRB lab-user@hypervisor
----

You can now create a file called `config-qcow2.json` with the following contents, replacing "SSHKEY" 
in the `key` field with the contents of `~/.ssh/id_rsa.pub` from your system:

[source,json]
----
{
  "blueprint": {
    "customizations": {
      "user": [
        {
          "name": "lab-user",
          "password": "lb1506",
          "key": "SSHKEY",
          "groups": [
            "wheel"
          ]
        }
      ]
    }
  }
}
----

This configuration blueprint creates a user `lab-user` with the password `lb1506` and the ssh key in the generated virtual machine image.

NOTE: For your convenience, a config file has already been generated with the ssh key for your lab host in `config/config-qcow2.json` so
you can just use that with `cp config/config-qcow2.json config-qcow2.json`.

[#create]
== Create the virtual machine image

First, you want to make sure the bootc image is available to the local registry:

[source,bash]
----
skopeo inspect docker://summit.registry/lb1506:bootc | jq '.Digest'
"sha256:655721ff613ee766a4126cb5e0d5ae81598e1b0c3bcf7017c36c4d72cb092fe9"
----

To convert from an OCI image to a disk image, we have a special version of image builder that has support for `bootc`. This 
`bootc-image-builder` itself runs as a container, and as a result needs addtional Capabilities and to be run as root.

Try to generate the image now:

NOTE: This could take 5+ minutes to complete.
[source,bash]
----
sudo podman run --rm --privileged \
        --volume .:/output \
        --volume ./config-qcow2.json:/config.json \
        registry.redhat.io/rhel9/bootc-image-builder:latest \
        --type qcow2 --config /config.json \
        --tls-verify=false \
        summit.registry/lb1506:bootc
----

A brief explanation of the arguments used for `podman` and `bootc-image-buider`:

  * `--rm` -> do not keep the build container after execution finishes
  * `--privileged` -> add capabilitiesrequired to build the image
  * `--volume` -> podman will map these local directories or files to the container
  * `registry.redhat.io/rhel9/bootc-image-builder:latest` -> the image builder container image

From here, these arguments passed to `bootc-image-builder`

  * `--type qcow2` -> the type of image to build
  * `--config /config.json` -> the json configuration file used; please note this is relative to the container filesystem
  * `--tls-verify=false` -> the registry we are running is local and it has self signed certificates; this flag would not be needed with `quay.io` for example
  * `summit.registry/lb1506:bootc` -> the image we are trying to pack into qcow2

Once this completes, you will find the image is the `qcow2/` directory:

NOTE: For your convenience, this part of the exercise is automated by using the `make qcow CONTAINER=summit.registry/lb1506:bootc` command.

[source,bash]
----
ls -lah qcow2/disk.qcow2
----

The output should be similar to:

[source]
----
-rw-r--r--. 1 root root 945M May  2 06:10 qcow2/disk.qcow2
----

[#create-vm]
== Create the virtual machine

The creation of virtual machines is out of scope for this lab, so we have provided a convenience command in the Makeile.
We've detailed the commnds being run so you can follow along with what is happening. If you like, feel free to run the
`virt-install` command on your own instead of using the `make` target.  

[source,bash]
----
make vm-qcow
----

For reference, the manual command is (*you do not need to run this command*):

[source,bash]
----
sudo cp qcow2/disk.qcow2 /var/lib/libvirt/images/summit/qcow-vm.qcow2
virt-install --connect qemu:///system \
                --name qcow \
                --disk /var/lib/libvirt/images/summit/qcow-vm.qcow2 \
                --import \
                --network "network=summit-network,mac=de:ad:be:ef:01:03" \
                --memory 4096 \
                --graphics none \
                --osinfo rhel9-unknown \
                --noautoconsole \
                --noreboot
virsh --connect qemu:///system start qcow
----

If `make vm-qcow` was successful, you should see the final line of output like this:

[source,bash]
----
Domain 'qcow' started

----

Check to make sure the virtual machine running:

[source,bash]
----
virsh --connect qemu:///system list

 Id   Name                State
------------------------------------
 5    qcow-vm             running
----

[#test]
== Test and login to the virtual machine

Congratulations, you are running a bootc virtual machine!  Now that the virtual machine is up 
and running, you can see if the webserver behaves as expected.

----
curl http://qcow-vm
----

And the results should be the "Hello Red Hat" string defined in the Containerfile.

You can now login to the virtual machine.

----
ssh lab-user@qcow-vm
----

NOTE: If the ssh key is not automatically picked up, use the password defined in the JSON file at the beginning of this lab (by default `lb1506`).

Once you have logged in, you can inspect the bootc status (the password for `sudo` is `lb1506`):

[source,bash]
----
sudo bootc status
----

The output should look similar to this:

[source,yaml]
----
apiVersion: org.containers.bootc/v1alpha1
kind: BootcHost
metadata:
  name: host
spec:
  image:
    image: summit.registry/lb1506:bootc
    transport: registry
  bootOrder: default
status:
  staged: null
  booted:
    image:
      image:
        image: summit.registry/lb1506:bootc
        transport: registry
      version: 9.20240501.0
      timestamp: null
      imageDigest: sha256:0a3daed6e31c2f2917e17ea994059e1aaee0481fe16836c118c5e1d10a87365c
    cachedUpdate: null
    incompatible: false
    pinned: false
    ostree:
      checksum: 008e3bef805f25224f591240627bea2a06ce12b25494836c2dab7d1b0a1691a8
      deploySerial: 0
  rollback: null
  rollbackQueued: false
  type: bootcHost
----

From the output of `bootc status`, find the block that starts with `booted`. This block provides information about 
the current image in use. You can see that image is listed as `summit.registry/lb1506:bootc`.

You can explore the virtual machine before moving on to the next section:

  * `systemctl status httpd` -> see the `httpd` service we have enabled in the Containerfile
  * `cat /var/www/html/index.html` -> see the index.html file we have created in the Containerfile

Before proceeding, make sure you have logged out of the virtual machine:

[source,bash]
----
logout
----

The prompt should read `[lab-user@hypervisor rh-summit-2024-lb1506]$` before continuing.
